version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.9"
  jobs:
    pre_build:
      - make pre-docs

sphinx:
  configuration: doc/sphinx/source/conf.py

python:
  install:
    - method: pip
      path: .
    - requirements: doc/requirements.txt
